Fix licensing.
OWASP/cornucopia pull request #489
Opened 2024-05-07 18:54 UTC by sydseter

WIP

2024-05-07 19:12 UTC, sydseter commented
Thought I take the initiative here. The current changes that I made is probably wrong. It would be great if you could give me some directions. I understood that part of the content was Apache 2.0 licensed. If so, which part?
Having both the "CC-BY-SA-3.0" and "Apache 2.0" licenses at the base of the repo without any note like now, is not a good idea. If most of the content is licensed under  "CC-BY-SA-3.0" we just need to note where that is not the case as these licenses not is considered to be compatible under the CC-BY-SA-3.0 terms.

2024-05-10 07:50 UTC, rewtd requested changes

2024-05-10 07:50 UTC, rewtd commented on README.md
> +Text and code mapping for OWASP Cornucopia Website App Edition is licensed under [Apache License 2.0](./source/LICENSE.md)
I think the original licence was Apache License 2.0 - but I'd like to make the Website App Edition CC-BY-SA-3.0 same as the rest.

2024-05-10 09:03 UTC, rewtd commented on README.md
> +Text and code mapping for OWASP Cornucopia Website App Edition is licensed under [Apache License 2.0](./source/LICENSE.md)
I've updated things to reflect that. But... have I done it right?

2024-05-10 09:23 UTC, sydseter commented on README.md
> +Text and code mapping for OWASP Cornucopia Website App Edition is licensed under [Apache License 2.0](./source/LICENSE.md)
Great! Looks good to me.

2024-05-10 09:24 UTC, sydseter commented on README.md
> +Text and code mapping for OWASP Cornucopia Website App Edition is licensed under [Apache License 2.0](./source/LICENSE.md)
@rewtd since I opened the pull-request, you need to approve it.

2024-05-10 09:24 UTC, rewtd approved these changes

2024-05-10 09:25 UTC, merged